/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessageLinksRouteImport } from './routes/_authenticated/message-links'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBotsRouteImport } from './routes/_authenticated/bots'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiBotRouteImport } from './routes/_authenticated/ai-bot'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedInboxPhoneRouteImport } from './routes/_authenticated/inbox.$phone'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessageLinksRoute =
  AuthenticatedMessageLinksRouteImport.update({
    id: '/message-links',
    path: '/message-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsRoute = AuthenticatedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiBotRoute = AuthenticatedAiBotRouteImport.update({
  id: '/ai-bot',
  path: '/ai-bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)
const AuthenticatedInboxPhoneRoute = AuthenticatedInboxPhoneRouteImport.update({
  id: '/$phone',
  path: '/$phone',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/ai-bot': typeof AuthenticatedAiBotRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/connect': typeof AuthenticatedConnectRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/message-links': typeof AuthenticatedMessageLinksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/inbox/$phone': typeof AuthenticatedInboxPhoneRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/ai-bot': typeof AuthenticatedAiBotRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/message-links': typeof AuthenticatedMessageLinksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/inbox/$phone': typeof AuthenticatedInboxPhoneRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/ai-bot': typeof AuthenticatedAiBotRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bots': typeof AuthenticatedBotsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/message-links': typeof AuthenticatedMessageLinksRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/inbox/$phone': typeof AuthenticatedInboxPhoneRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/ai-bot'
    | '/analytics'
    | '/bots'
    | '/campaigns'
    | '/connect'
    | '/contacts'
    | '/dashboard'
    | '/inbox'
    | '/message-links'
    | '/notifications'
    | '/plans'
    | '/settings'
    | '/support'
    | '/templates'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/inbox/$phone'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agents'
    | '/ai-bot'
    | '/analytics'
    | '/bots'
    | '/connect'
    | '/contacts'
    | '/dashboard'
    | '/inbox'
    | '/message-links'
    | '/notifications'
    | '/plans'
    | '/settings'
    | '/support'
    | '/templates'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/inbox/$phone'
    | '/campaigns'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/ai-bot'
    | '/_authenticated/analytics'
    | '/_authenticated/bots'
    | '/_authenticated/campaigns'
    | '/_authenticated/connect'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/message-links'
    | '/_authenticated/notifications'
    | '/_authenticated/plans'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/templates'
    | '/auth/forgot'
    | '/auth/reset-password'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/inbox/$phone'
    | '/_authenticated/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/message-links': {
      id: '/_authenticated/message-links'
      path: '/message-links'
      fullPath: '/message-links'
      preLoaderRoute: typeof AuthenticatedMessageLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots': {
      id: '/_authenticated/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedBotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-bot': {
      id: '/_authenticated/ai-bot'
      path: '/ai-bot'
      fullPath: '/ai-bot'
      preLoaderRoute: typeof AuthenticatedAiBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
    '/_authenticated/inbox/$phone': {
      id: '/_authenticated/inbox/$phone'
      path: '/$phone'
      fullPath: '/inbox/$phone'
      preLoaderRoute: typeof AuthenticatedInboxPhoneRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
  }
}

interface AuthenticatedCampaignsRouteChildren {
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedCampaignsRouteChildren: AuthenticatedCampaignsRouteChildren =
  {
    AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
    AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
    AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  }

const AuthenticatedCampaignsRouteWithChildren =
  AuthenticatedCampaignsRoute._addFileChildren(
    AuthenticatedCampaignsRouteChildren,
  )

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxPhoneRoute: typeof AuthenticatedInboxPhoneRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxPhoneRoute: AuthenticatedInboxPhoneRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAiBotRoute: typeof AuthenticatedAiBotRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBotsRoute: typeof AuthenticatedBotsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRouteWithChildren
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedMessageLinksRoute: typeof AuthenticatedMessageLinksRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAiBotRoute: AuthenticatedAiBotRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBotsRoute: AuthenticatedBotsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRouteWithChildren,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedMessageLinksRoute: AuthenticatedMessageLinksRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
